apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: skies
data:
  config.yaml: |
    apisix:
      node_listen:
        - 9080
        - 9443
    etcd:
      host:
        - "http://etcd.skies.svc.cluster.local:2379"
      prefix: "/apisix"
      timeout: 30
    plugin_attr:
      prometheus:
        export_uri: /apisix/prometheus/metrics
  nginx.conf: |
    worker_processes  1;
    error_log  logs/error.log warn;
    pid        logs/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;
      include /usr/local/apisix/conf/nginx.conf;
    }
