apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: skies
spec:
  ports:
    - port: 2379
      name: client
  clusterIP: None
  selector:
    app: etcd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: skies
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      nodeSelector:
        skies/node: perimeter
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.13
          command:
            - /usr/local/bin/etcd
            - --data-dir=/var/lib/etcd
            - --advertise-client-urls=http://0.0.0.0:2379
            - --listen-client-urls=http://0.0.0.0:2379
          ports:
            - containerPort: 2379
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib/etcd
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
  