apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: skies
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tier: db
        skies/group: db
    spec:
      nodeSelector:
        node-role: thera
      containers:
        - name: redis
          image: redis:8-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 11Gi
        storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv
spec:
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /mnt/data/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role
              operator: In
              values:
                - thera

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: skies
spec:
  selector:
      app: redis
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31701
      protocol: TCP