kind: Deployment
apiVersion: apps/v1
metadata:
  name: festival
  labels:
    app: festival

spec:
  replicas: 1
  selector:
    matchLabels:
      app: festival
  template:
    metadata:
      labels:
        app: festival
    spec:
      containers:
        - name: festival
          image: skies/festival:v1.6.0
          imagePullPolicy: Never
          ports:
            - name: web
              containerPort: 80