apiVersion: v1
kind: Pod
metadata:
  name: db-storage-prep
  namespace: skies
spec:
  nodeSelector:
    node-role: thera
  containers:
    - name: busybox
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ]
      securityContext:
        privileged: true
      volumeMounts:
        - name: host-root
          mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /
        type: Directory
  restartPolicy: Never
