apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: skies
spec:
  selector:
    app: apisix
  ports:
    - name: http
      port: 80
      targetPort: 9080
    - name: https
      port: 443
      targetPort: 9443
    - name: prometheus
      port: 9091
      targetPort: 9091
  type: NodePort
