# ConfigMap will be created separately from the default.conf file
# Use: kubectl create configmap umbreon-config --from-file=default.conf=04-umbra/default.conf -n skies

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umbreon
  namespace: skies
  labels:
    app: umbreon
    tier: proxy
    skies/group: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umbreon
  template:
    metadata:
      labels:
        app: umbreon
        tier: proxy
        skies/group: web
    spec:
      nodeSelector:
        skies/code: umbra
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
            - containerPort: 443
              hostPort: 443
              name: https
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-logs
              mountPath: /var/log/nginx
            - name: letsencrypt-certs
              mountPath: /etc/letsencrypt
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: nginx-config
          configMap:
            name: umbreon-config
        - name: nginx-logs
          emptyDir: {}
        - name: letsencrypt-certs
          hostPath:
            path: /mnt/data/letsencrypt
            type: Directory
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: umbreon
  namespace: skies
  labels:
    app: umbreon
    tier: proxy
spec:
  selector:
    app: umbreon
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https

  # Uncomment below if you have TLS certificates configured
  # tls:
  #   - hosts:
  #       - admin.skies.local
  #     secretName: umbreon-tls
  #     secretName: nginx-umbra-tls
